export type Category = {
  id: string
  label: string
  phrases: string[]
}

/** Template slots combine into phrases that read naturally in any pairing. */
export type Template = {
  id: string
  label: string
  pattern: string
  parts: Record<string, string[]>
}

export const CATEGORIES: Category[] = [
  {
    id: 'idioms',
    label: 'Idioms',
    phrases: [
      'Break the ice',
      'Piece of cake',
      'Hit the nail on the head',
      'Under the weather',
      'Bite the bullet',
      'Spill the beans',
      'Once in a blue moon',
      'The ball is in your court',
      'Burning the midnight oil',
      'Let the cat out of the bag',
      'Costs an arm and a leg',
      'Barking up the wrong tree',
      'A blessing in disguise',
      'Cut to the chase',
      'Back to the drawing board',
    ],
  },
  {
    id: 'movies',
    label: 'Movies',
    phrases: [
      'The Empire Strikes Back',
      'Jurassic Park',
      'The Grand Budapest Hotel',
      'Spirited Away',
      'Back to the Future',
      'The Princess Bride',
      'Raiders of the Lost Ark',
      'Finding Nemo',
      'The Silence of the Lambs',
      'Groundhog Day',
      'Inside Out',
      'The Truman Show',
      'Mad Max Fury Road',
      'Dead Poets Society',
    ],
  },
  {
    id: 'places',
    label: 'Places',
    phrases: [
      'Great Barrier Reef',
      'Niagara Falls',
      'The Northern Lights',
      'Machu Picchu',
      'Grand Canyon',
      'Mount Kilimanjaro',
      'Sahara Desert',
      'Victoria Harbour',
      'Amazon Rainforest',
      'Golden Gate Bridge',
      'Easter Island',
      'Black Forest',
    ],
  },
  {
    id: 'everyday',
    label: 'Everyday things',
    phrases: [
      'Cup of coffee',
      'Washing machine',
      'Bicycle helmet',
      'Alarm clock',
      'Reading glasses',
      'Shopping trolley',
      'Kitchen sink',
      'Umbrella stand',
      'Front door key',
      'Chocolate biscuit',
      'Garden shed',
      'Paper aeroplane',
    ],
  },
  {
    id: 'science-class',
    label: 'Science class',
    phrases: [
      'Carbon dioxide',
      'Water cycle',
      'Solar system',
      'Photosynthesis',
      'Food chain',
      'Solar eclipse',
      'Lunar eclipse',
      'Water vapour',
      'Air pressure',
      'Magnetic field',
      'Electric circuit',
      'Boiling point',
      'Melting point',
      'Evaporation',
      'Condensation',
      'Gravity',
      'Friction',
      'Habitat',
      'Ecosystem',
      'Predator',
      'Mammal',
      'Reptile',
      'Amphibian',
      'Insect',
      'Chrysalis',
      'Pollination',
      'Germination',
      'Chlorophyll',
      'Thermometer',
      'Microscope',
      'Telescope',
      'Skeleton',
      'Digestion',
      'Oxygen',
      'Hydrogen',
      'Bacteria',
      'Lever',
      'Pulley',
      'Circuit board',
      'Life cycle',
    ],
  },
  {
    id: 'maths-class',
    label: 'Maths class',
    phrases: [
      'Prime number',
      'Right angle',
      'Square root',
      'Decimal point',
      'Number line',
      'Times table',
      'Even number',
      'Odd number',
      'Multiplication',
      'Division',
      'Subtraction',
      'Addition',
      'Fraction',
      'Percentage',
      'Perimeter',
      'Diameter',
      'Radius',
      'Triangle',
      'Rectangle',
      'Pentagon',
      'Hexagon',
      'Octagon',
      'Cylinder',
      'Sphere',
      'Symmetry',
      'Average',
      'Estimate',
      'Equation',
      'Remainder',
      'Denominator',
      'Numerator',
      'Parallel lines',
      'Acute angle',
      'Obtuse angle',
      'Probability',
      'Bar chart',
      'Pie chart',
      'Place value',
      'Whole number',
      'Measuring tape',
    ],
  },
  {
    id: 'geography-class',
    label: 'Geography class',
    phrases: [
      'Tropical rainforest',
      'Coral reef',
      'Mountain range',
      'River delta',
      'Sand dune',
      'Ice cap',
      'Time zone',
      'Equator',
      'Continent',
      'Peninsula',
      'Volcano',
      'Earthquake',
      'Glacier',
      'Climate',
      'Compass',
      'Longitude',
      'Latitude',
      'Capital city',
      'Island',
      'Desert',
      'Savanna',
      'Tundra',
      'Canyon',
      'Waterfall',
      'Harbour',
      'Estuary',
      'Plateau',
      'Monsoon',
      'Rain shadow',
      'Water table',
      'Fossil fuel',
      'Contour line',
      'Grid reference',
      'Population',
      'Settlement',
      'Erosion',
      'Landslide',
      'Tributary',
      'Wetland',
      'Ozone layer',
    ],
  },
  {
    id: 'history-class',
    label: 'History class',
    phrases: [
      'Ancient Egypt',
      'Stone Age',
      'Bronze Age',
      'Iron Age',
      'Roman Empire',
      'Great Wall',
      'Pyramid',
      'Pharaoh',
      'Castle',
      'Drawbridge',
      'Explorer',
      'Sailing ship',
      'Steam engine',
      'Printing press',
      'Archaeology',
      'Artefact',
      'Museum',
      'Timeline',
      'Century',
      'Decade',
      'Emperor',
      'Dynasty',
      'Hieroglyph',
      'Papyrus',
      'Aqueduct',
      'Colosseum',
      'Mosaic',
      'Parchment',
      'Compass rose',
      'Trade route',
      'Silk Road',
      'Lighthouse',
      'Windmill',
      'Marketplace',
      'Cathedral',
      'Monastery',
      'Scroll',
      'Chariot',
      'Amphitheatre',
      'Ancient Greece',
    ],
  },
]

export const TEMPLATES: Template[] = [
  {
    id: 'creature',
    label: 'Odd creatures',
    pattern: '{adjective} {animal}',
    parts: {
      adjective: [
        'Grumpy',
        'Dancing',
        'Invisible',
        'Electric',
        'Velvet',
        'Thunderous',
        'Polite',
        'Rusty',
        'Midnight',
        'Curious',
        'Clumsy',
        'Golden',
      ],
      animal: [
        'Penguin',
        'Octopus',
        'Hedgehog',
        'Flamingo',
        'Walrus',
        'Chameleon',
        'Badger',
        'Otter',
        'Pelican',
        'Tortoise',
        'Squirrel',
        'Jellyfish',
      ],
    },
  },
  {
    id: 'place',
    label: 'Imaginary places',
    pattern: 'The {adjective} {place}',
    parts: {
      adjective: [
        'Forgotten',
        'Crystal',
        'Whispering',
        'Crooked',
        'Silver',
        'Endless',
        'Frozen',
        'Hidden',
        'Scarlet',
        'Quiet',
      ],
      place: [
        'Library',
        'Lighthouse',
        'Marketplace',
        'Observatory',
        'Bridge',
        'Orchard',
        'Harbour',
        'Staircase',
        'Greenhouse',
        'Workshop',
      ],
    },
  },
]
